import{a as b,S as v,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const S="49650117-af312fdd4c8d669445c27b54b",P="https://pixabay.com/api/",q=16;async function E(r,o){return(await b.get(P,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q}})).data}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),a=document.querySelector(".load-more");let $=new v(".gallery a");function B(r){const o=r.map(n=>n.isPlaceholder?'<li class="gallery-item placeholder"></li>':`
        <li class="gallery-item">
          <a href="${n.largeImageURL}">
            <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p>👍 ${n.likes}</p>
            <p>👁️ ${n.views}</p>
            <p>💬 ${n.comments}</p>
            <p>⬇️ ${n.downloads}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",o),$.refresh()}function M(){h.innerHTML=""}function A(){y.classList.remove("is-hidden")}function p(){y.classList.add("is-hidden")}function x(){a&&a.classList.remove("is-hidden")}function g(){a&&a.classList.add("is-hidden")}const d=document.querySelector(".form"),u=document.querySelector(".gallery"),f=document.querySelector(".load-more");let L="",s=1,m=0;p();d.addEventListener("submit",async r=>{r.preventDefault();const o=d.elements.searchQuery.value.trim();o&&(L=o,s=1,M(),g(),A(),await w())});f&&f.addEventListener("click",async()=>{s+=1,await w()});async function w(){try{const r=await E(L,s);if(m=r.totalHits,r.hits.length===0&&s===1){c.info({title:"😔",message:"No images found. Try a different keyword."});return}B(r.hits);const o=Math.ceil(m/16);if(s<o)x();else{g(),c.info({title:"📦",message:"We're sorry, but you've reached the end of search results."});const n=r.hits.length%4;if(n!==0){const i=4-n;Array.from({length:i},()=>{const t=document.createElement("li");t.classList.add("gallery-item","placeholder"),u.appendChild(t)}).forEach(t=>u.appendChild(t))}}s>1&&O()}catch{c.error({title:"Error",message:"Something went wrong. Please try again."})}finally{setTimeout(()=>{p()},500)}}function O(){const r=document.querySelector(".gallery li");if(!r)return;const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
