import{a as w,S as b,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="49650117-af312fdd4c8d669445c27b54b",S="https://pixabay.com/api/",P=15;async function q(r,o){return(await w.get(S,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P}})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),a=document.querySelector(".load-more");let E=new b(".gallery a");function $(r){const o=r.map(n=>n.isPlaceholder?'<li class="gallery-item placeholder"></li>':`
        <li class="gallery-item">
          <a href="${n.largeImageURL}">
            <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p>👍 ${n.likes}</p>
            <p>👁️ ${n.views}</p>
            <p>💬 ${n.comments}</p>
            <p>⬇️ ${n.downloads}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",o),E.refresh()}function B(){m.innerHTML=""}function M(){y.classList.remove("is-hidden")}function h(){y.classList.add("is-hidden")}function A(){a&&a.classList.remove("is-hidden")}function p(){a&&a.classList.add("is-hidden")}const u=document.querySelector(".form"),x=document.querySelector(".gallery"),f=document.querySelector(".load-more");let g="",s=1,d=0;h();u.addEventListener("submit",async r=>{r.preventDefault();const o=u.elements.searchQuery.value.trim();o&&(g=o,s=1,B(),p(),M(),await L())});f&&f.addEventListener("click",async()=>{s+=1,await L()});async function L(){try{const r=await q(g,s);if(d=r.totalHits,r.hits.length===0&&s===1){c.info({title:"😔",message:"No images found. Try a different keyword."});return}$(r.hits);const o=Math.ceil(d/15);if(s<o)A();else{p(),c.info({title:"📦",message:"We're sorry, but you've reached the end of search results."});const n=d%15%4;if(n!==0){const i=4-n;Array.from({length:i},()=>{const t=document.createElement("li");return t.classList.add("gallery-item","placeholder"),t}).forEach(t=>x.appendChild(t))}}s>1&&O()}catch{c.error({title:"Error",message:"Something went wrong. Please try again."})}finally{setTimeout(()=>{h()},500)}}function O(){const r=document.querySelector(".gallery li");if(!r)return;const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
